x-go-service: &go-service
  env_file:
    - ./.env
  build:
    context: .
    dockerfile: backend/Dockerfile.dev
    args:
      APP_UID: ${UID:-1000}
      APP_GID: ${GID:-1000}
  working_dir: /app/backend
  environment:
    HOME: /home/app
    GOMODCACHE: /home/app/go/pkg/mod
    GOCACHE: /home/app/.cache/go-build
    XDG_CACHE_HOME: /home/app/.cache
  volumes:
    - ./backend:/app/backend
    - ./docker/backend/cache/gomod:/home/app/go/pkg/mod
    - ./docker/backend/cache/gocache:/home/app/.cache/go-build
    - ./rules:/app/rules:ro
  depends_on:
    postgres:
      condition: service_healthy
    clickhouse:
      condition: service_healthy
services:
  postgres:
    container_name: ${SERVICE_PREFIX:-sw_}pgsql
    image: postgres:18beta3
    ports:
      - "${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-swearjar}
      POSTGRES_USER: ${POSTGRES_USER:-swearjar}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-swearjar}
      PGPORT: ${POSTGRES_PORT:-5432}
    volumes:
      - "./backend/docker/pgsql/00-create-users.sh:/docker-entrypoint-initdb.d/00-create-users.sh:ro"
      - "./backend/docker/pgsql/init.sql:/docker-entrypoint-initdb.d/100-init.sql:ro"
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-swearjar} -d ${POSTGRES_DB:-swearjar} -p ${POSTGRES_PORT:-5432}",
        ]
      interval: 3s
      timeout: 3s
      retries: 20
    env_file:
      - ./.env

  clickhouse:
    container_name: ${SERVICE_PREFIX:-sw_}clickhouse
    image: clickhouse/clickhouse-server:latest
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - chdata:/var/lib/clickhouse
      - "./backend/docker/clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql:ro"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:8123/ping | grep -q 'Ok.'"]
      interval: 5s
      timeout: 5s
      retries: 30
    env_file:
      - ./.env
  clickhouseui:
    env_file:
      - ./.env
    container_name: ${SERVICE_PREFIX:-sw_}clickhouseui
    image: ghcr.io/caioricciuti/ch-ui:latest
    restart: always
    ports:
      - "5302:5521"
    environment:
      VITE_CLICKHOUSE_URL: "http://localhost:8123"
      VITE_CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      VITE_CLICKHOUSE_PASS: ${CLICKHOUSE_PASSWORD}
      VITE_CLICKHOUSE_USE_ADVANCED: "true"
      VITE_CLICKHOUSE_REQUEST_TIMEOUT: "30000"
  adminer:
    env_file:
      - ./.env
    container_name: ${SERVICE_PREFIX:-sw_}adminer
    build:
      context: ./backend/docker/adminer
      dockerfile: Dockerfile
    ports:
      - "${SERVICE_PORT_ADMINER:-5300}:8080"
    depends_on:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=pgsql
    attach: false
  api:
    <<: *go-service
    container_name: ${SERVICE_PREFIX:-sw_}api
    command: sh -c "air -c cmd/swearjar-api/.air.toml"
    ports:
      - "${CORE_API_PORT:-8080}:${CORE_API_PORT:-4000}"
    volumes:
      - ./backend:/app/backend
      - ./backend/data:/var/lib/swearjar/gharchive
      - ./rules:/app/rules:ro
  web:
    env_file:
      - ./.env
    container_name: ${SERVICE_PREFIX:-sw_}web
    build:
      context: .
      dockerfile: frontend/web/Dockerfile.dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    working_dir: /workspace/frontend/web
    ports:
      - "5173:5173"
    volumes:
      - .:/workspace
    environment:
      - NODE_ENV=development
      - PORT=5173
      - NPM_CONFIG_CACHE=/home/frontend/.npm
    command: ["sh", "-c", "npm ci && npm run dev"]
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "http=require('http');http.get('http://localhost:5173',r=>process.exit(r.statusCode===200?0:1)).on('error',()=>process.exit(1))",
        ]
      interval: 60s
      timeout: 3s
volumes:
  pgdata:
  chdata:
