root = "/app/backend"
tmp_dir = ".air"

[build]
cmd = """
# Ensure output dir exists
mkdir -p ./internal/services/api/docs

# Let swag recursively scan the repo, but don't use 'go list' for package discovery
swag init \
  --dir . \
  --generalInfo cmd/swearjar-api/main.go \
  --output internal/services/api/docs \
  --parseGoList=false \
  --parseDependency \
  --parseInternal \
  --parseDepth 3 \
  --exclude internal/services/api/docs,bin,.git,vendor \
  --v3.1

# Build to a guaranteed-writable path inside the container
GOEXPERIMENT=jsonv2 go build -tags swag -o /tmp/api ./cmd/swearjar-api
"""
bin = "/tmp/api"

include_ext = ["go", "yaml", "yml", "toml"]

include_dir = [
  "cmd",
  "internal",
]

exclude_dir = ["internal/services/api/docs", "bin", ".git", "vendor"]

delay = 300

[log]
time = true
color = true
level = "info"

[run]
cmd = "/tmp/api"
